version: '3'

services:
  vuln-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
