version: '3'

services:
  vuln-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-app
    ports:
      - "8084:5000"
    volumes:
      - ./:/app
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
